version: '3.1'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    image: yiisoftware/yii2-php:8.1-apache
    ports:
      - 8000:80
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
      - .:/var/www/html
    environment:
        DDBB_NAME: ${POSTGRES_DB}
        DDBB_HOST: db
        DDBB_PASSWORD: ${POSTGRES_PASSWORD}
        PHP_USER_ID: 1001
    depends_on:
      - db
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_USERNAME=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}